### ISSUE TITLE
Scrollbar style not working

### ISSUE THREAD

**Issue by NullDev** [EpticMC/Commander-IDE#5]
The CSS rules for the webkit scrollbar do not get applied.

Code: 

```CSS
::-webkit-scrollbar-track { background: #111;    }
::-webkit-scrollbar-thumb { background: #F04646; }
```

On <a href="https://github.com/EpticMC/Commander-IDE/blob/master/layouts/main.css#L7-L8">Line 7 to Line 8</a> in <a href="https://github.com/EpticMC/Commander-IDE/blob/master/layouts/main.css">main.css</a>
