### ISSUE TITLE
Editor font isn't monospace

### ISSUE THREAD

**Issue by NullDev** [EpticMC/Commander-IDE#7]
The font inside the editor is not monospace because of 

```CSS
* { font-family: 'Raleway', sans-serif; }
```
On <a href="https://github.com/EpticMC/Commander-IDE/blob/master/layouts/main.css#L11">Line 11</a> in <a href="https://github.com/EpticMC/Commander-IDE/blob/master/layouts/main.css">main.css</a>

**Comment by NullDev** [comment]
Fixed by targeting all child elements of the editor with

```css
monaco-editor * { 
    font-family: "Droid Sans Mono", "Courier New", monospace, "Droid Sans Fallback" !important; 
}
```

Commit: https://github.com/EpticMC/Commander-IDE/commit/2712b8f207f280073582917aaa1258f0501269ff
